
<link rel="stylesheet" type="text/css" href="<?=HOME_PATH?>css/documentation-layout.css">
<link rel="stylesheet" type="text/css" href="<?=HOME_PATH?>css/document-menu.css">

</head>

<body>
<div class="my-wrapper">
	<div class="my-title">

	</div>
	<div class="my-header">
		<h2>minif4PHP</h2>
		<div class="dropdown">
		<button class="dropbtn">GET MINIF </button>
		</div>
		<div class="dropdown">
		<button class="dropbtn">ABOUT <i class="fa fa-chevron-right" aria-hidden="true"></i> </button>
		<div class="dropdown-content">
			<a href="#">Link 1</a>
			<a href="#">Link 2</a>
			<a href="#">Link 3</a>
		</div>
		</div>
		<div class="dropdown">
		<button class="dropbtn">COMMUNITY <i class="fa fa-chevron-right" aria-hidden="true"></i> </button>
		<div class="dropdown-content">
			<a href="#">Link 1</a>
			<a href="#">Link 2</a>
			<a href="#">Link 3</a>
		</div>
		</div>
		<div class="dropdown">
		<button class="dropbtn">DOCUMENTATION <i class="fa fa-chevron-right" aria-hidden="true"></i> </button>
		<div class="dropdown-content">
			<a href="#">Link 1</a>
			<a href="#">Link 2</a>
			<a href="#">Link 3</a>
		</div>
		</div>
		<div class="dropdown">
		<button class="dropbtn">HELP</button>
		</div>
	</div>


	<div class="my-content">
		<img src="https://insanelab.com/wp-content/uploads/2017/07/laravel_php_framework_2017_top-1120x458.png" width="100%">
		<h2>Mini Framework for PHP</h2>
		<p>Minif library latest update on Sept, 27, 2017.</p>
		<?php /*
			foreach ($list_lib as $files){
				echo "<li><a href='#'>".$files['filename']." - ".$files['filesize2'] ."</a></li>";
			} */
		?>
		<?php /*
			echo "<br><h6>".$fileLib->file_count." File in library with total ".$fileLib->file_totalSizeKB." KByte</h6>";  */
		?>
	</div>
	<div class="my-subcontent1">
		<h4>Slim</h4>
		<p>Slim size of framework that can use more faster than before</p>
	</div>
	<div class="my-subcontent2">
		<h4><i class="fa fa-twitter" style="color:#0084b4"> </i>Reusable Code</h4>
		<p>Reusable code can make you finished project more faster than before</p>
	</div>
	<div class="my-subcontent3">
		<h4>Documentation</h4>
		<p>Read minif documentation by click this link below</p>
		<a href="doc/minif.pdf" target="blank">Document</a>
	</div>

	<div class="my-sidebar">
		<h4>Download</h4>
		<p>Download Latest Framework is minif2.13</p>
		<button type="button" class="btn btn-primary">Download minif 2.13</button>
		<p>This files generated by databases</p>
	</div>

	<div class="my-footer">
	</div>
	<div class="my-footer-note">
		<h4>Credits</h4>
		<p>Designed and built with all the love in the world by @mdo and @fat. Maintained by the core team with the help of our contributors.
Currently v4.0.0-alpha.6. Code licensed MIT, docs CC BY 3.0.</p>
	</div>
</div>
</body>
</html>
